pars <- orderly::orderly_parameters(a = NULL)
orderly::orderly_dependency("parameters", "latest", c(input.rds = "data.rds"))
orderly::orderly_artefact("result.rds", description = "Processed data")
d <- readRDS("input.rds")
saveRDS(lapply(d, function(x) x * 2), "result.rds")
