orderly2::orderly_dependency("data", "latest", c(input.rds = "data.rds"))
orderly2::orderly_artefact(description = "Final plot", files = "graph.png")
d <- readRDS("input.rds")
png("graph.png")
plot(y ~ x, d)
dev.off()
