##' Find, and delete, file that were generated by running a report.
##' Until you're comfortable with what this will do, you are strongly
##' recommended to run `orderly_cleanup_status` first to see what will
##' be deleted.
##'
##' After file deletion, we look through and remove all empty
##' directories; orderly2 has similar semantics here to git where
##' directories are never directly tracked.
##'
##' @section Notes for user of orderly1:
##'
##' In orderly1 this function has quite different semantics, because
##'   the full set of possible files is always knowable from the yaml
##'   file. So there, we start from the point of view of the list of
##'   files then compare that with the directory.
##'
##' @title Clean up source directory
##'
##' @param name Name of the report directory to clean (i.e., we look
##'   at `src/<name>` relative to your orderly root
##'
##' @inheritParams orderly_run
##'
##' @return An (currently unstable) object of class
##'   `orderly_cleanup_status` within which the element `delete`
##'   indicates files that would be deleted (for
##'   `orderly_cleanup_status`) or that were deleted (for
##'   `orderly_cleanup`)
##'
##' @author export
orderly_cleanup <- function(name = NULL, root = NULL, locate = TRUE) {
  status <- orderly_cleanup_status()
  if (length(status$delete) > 0) {
    withr::with_dir(status$path, fs::file_delete(status$delete))
  }
  delete_empty_directories(status$path)
  invisible(status)
}


##' @export
##' @rdname orderly_cleanup
orderly_cleanup_status <- function(name = NULL, root = NULL, locate = TRUE) {
  root <- orderly_root(root, locate)
  p <- get_active_packet()
  is_active <- !is.null(p)
  if (is_active) {
    stop("Don't call this with an acive packet...")
  }

  if (is.null(name)) {
    path <- getwd()
    root <- detect_orderly_interactive_path(path)$path
    name <- basename(path)
  } else {
    root <- orderly_root(root, locate)
    validate_orderly_directory(name, root, environment())
    path <- file.path(root$path, "src", name)
  }

  info <- orderly_read(path)
  files <- withr::with_dir(
    path,
    dir(all.files = TRUE, recursive = TRUE, no.. = TRUE))

  is_orderly <- files == "orderly.R"
  is_resource <- files %in% info$resources
  is_artefact <- files %in% unlist(lapply(info$artefacts, "[[", "files"))
  role <- cbind(orderly = is_orderly,
                resource = is_resource,
                global = FALSE,     # TODO
                dependency = FALSE, # TODO
                artefact = is_artefact)
  rownames(role) <- files

  ## TODO: always delete the log.json file!

  is_source <- row_any(role[, c("orderly", "resource"), drop = FALSE])
  is_derived <- !is_source &
    row_any(role[, c("global", "dependency", "artefact"), drop = FALSE])
  is_ignored <- path_is_git_ignored(path, repo)
  status <- cbind(source = is_source,
                  derived = is_derived,
                  ignored = is_ignored)
  rownames(status) <- files

  to_delete <- (is_derived | (!is.na(is_ignored) & is_ignored)) & !is_source
  delete <- files[to_delete]

  structure(list(name = name,
                 root = root,
                 path = path,
                 role = role,
                 status = status,
                 delete = delete),
            class = "orderly_cleanup_status")
}
